### ISSUE TITLE
Support for Azure DevOps new domain name

### ISSUE THREAD

**Issue by sachabrants** [zumwald/better-vsts-npm-auth#20]
Please support Azure DevOps new domain name.
"visualstudio.com" is hard coded in 2 places and prevent the tool to work with "pkgs.dev.azure.com/organization" instead of "organization.pkgs.visualstudio.com"

**Comment by roman4ak** [comment]
Hi,
Are there any plans for this feature?

**Comment by zumwald** [comment]
Sure I’ll find a few minutes to push this within the week.
