### ISSUE TITLE
How to revoke token access

### ISSUE THREAD

**Issue by ehills** [zumwald/better-vsts-npm-auth#37]
Hi there, less of an issue and more of a question..
I used your service this morning but now I wish to revoke the access/refresh token that was generated and that your site saw.
Is this possiblefrom azure devops? It doesnt appear to be (although my organisation might be disallowing it?).

I know you claim that your site doesn't see it but the security consious man in me wants to really make sure that is the case.

Cheers,
Ed

**Comment by zumwald** [comment]
Totally respect the skepticism, it's the right security stance for sure. You can revoke authorization for an app like so: https://intercom.help/appcenter/en/articles/1338717-i-have-connected-to-the-wrong-azure-devops-account-how-can-i-re-connect-to-the-correct-one
