### ISSUE TITLE
Web App Down

### ISSUE THREAD

**Issue by farflungfish** [zumwald/better-vsts-npm-auth#39]
Hi,

my team really appreciate the existence of this, it helps the development teams greatly.

Though today we noticed the web app which is used for this process appears to be down:

stateless-vsts-oauth.azurewebsites.net

![image](https://user-images.githubusercontent.com/10864357/113019955-07ede180-917a-11eb-92e4-fd906d39fdd1.png)

**Comment by melvsparks** [comment]
Yep, I'm having the same issue

**Comment by zumwald** [comment]
Outage was caused by my Azure account reaching its spending limit. I've removed the limit permanently to prevent this.

**Comment by thomasmattheussen** [comment]
The web app seems to be unavailable since today.
