### ISSUE TITLE
Update credentials

### ISSUE THREAD

**Issue by lydemann** [zumwald/better-vsts-npm-auth#53]
I can't update the credentials for Azure to use to generate the access tokens.

Even when following this guide for vsts-npm-auth, credential are still persisted:

https://stackoverflow.com/questions/43840562/update-vsts-npm-auth-with-new-username-and-password

**Comment by lydemann** [comment]
Managed to fix this by setting empty refresh token

```
better-vsts-npm-auth config set refresh_token DUMMY
```

**Comment by zumwald** [comment]
idk... if you're in a state where you want to reset your azure creds I'm not sure providing a "reset" command as a wrapper over deleting the refresh_token solves more problems than it creates by mixing the auth principals represented in the file. For those who find them in such a predicament running `--help` should lead them to `config delete` or another solution like you found.
