### ISSUE TITLE
Web App is Unreachable

### ISSUE THREAD

**Issue by grenadier117** [zumwald/better-vsts-npm-auth#57]
We've been using better-vsts-npm-auth for over a year now, but after running the command today we're receiving a 403 error that the site is down.

[https://stateless-vsts-oauth.azurewebsites.net/](https://stateless-vsts-oauth.azurewebsites.net/)

![Screen Shot 2022-08-10 at 12 03 36 PM](https://user-images.githubusercontent.com/16449505/183996502-4c7bbe90-df88-4df1-908c-8781edc22c5c.png)

**Comment by wibjorn** [comment]
Yep, same

**Comment by grenadier117** [comment]
@zumwald do you know the cause of this?

**Comment by zumwald** [comment]
Looks like a glitch caused all the resources in my azure subscription to be deleted. I will look into it within the next 24 hours.
