### ISSUE TITLE
Failed authentication 403 error

### ISSUE THREAD

**Issue by mightycannon** [zumwald/better-vsts-npm-auth#58]
I am running node on a windows 10 computer. 
I have had no issues using better-vsts-npm-auth until today. 
When I try to run the script I get this message
*****
We need user consent before this script can run.

Follow instructions in the browser window that just opened, or if a browser does not open,
manually browse to this url and follow the instructions there:

https://app.vssps.visualstudio.com/oauth2/authorize?client_id=DE516D90-B63E-4994-BA64-881EA988A9D2&response_type=Assertion&state=b2b1f0c5-70bb-4529-8759-5267f6b5cb52&scope=vso.packaging_write&redirect_uri=https://stateless-vsts-oauth.azurewebsites.net/oauth-callback

Then run better-vsts-npm-auth again after consent has been granted.
*****

following that link leads to a page with a 403 error. I have attached a screenshot of the error

![error-403](https://user-images.githubusercontent.com/16885209/184011217-dcf65c1c-e10e-4af4-9154-72e202d10ba7.PNG)

**Comment by awatertrevi** [comment]
Same here...

**Comment by grenadier117** [comment]
Linking this [issue](https://github.com/zumwald/better-vsts-npm-auth/issues/57)
