### ISSUE TITLE
npmAlwaysAuth should be set to true

### ISSUE THREAD

**Issue by AArnott** [zumwald/better-vsts-npm-auth#59]
Thank you for this awesome tool. It works great for yarn berry.... after I figured out that the `npmAlwaysAuth` setting in my repo .yarnrc.yml file was *not* copied to my user directory .yarnrc.yml file and copied it over myself.

My npm feed is a private one, so it always requires authentication. Without this setting, I get a 401 even though the auth token is right.

**Comment by zumwald** [comment]
IMO that's for the user to determine & manage. No need for this tool to be opinionated about that.

**Comment by AArnott** [comment]
Might there be a switch that can set it in the file then? For my script that runs your tool, I'd prefer the file it creates be ready for use rather than to have to edit the file right after your tool does.

**Comment by zumwald** [comment]
Sure I would accept a PR for that.
________________________________
