### ISSUE TITLE
{"Error":"invalid_request","ErrorDescription":"Client secret is expired."}

### ISSUE THREAD

**Issue by nandin-borjigin** [zumwald/better-vsts-npm-auth#61]
![image](https://user-images.githubusercontent.com/10903833/198960375-de8172a5-fc36-4ff4-938a-c7eb7a5478b5.png)
![image](https://user-images.githubusercontent.com/10903833/198960456-38f6bed6-e13e-4580-88f4-dd3598ef68b0.png)

**Comment by ChrisAnkowski** [comment]
Same issue for me.

**Comment by s3fs** [comment]
Same for me

**Comment by rmacedo88** [comment]
Same issue here

**Comment by olson-nathan** [comment]
There is a manual workaround [documented here](https://learn.microsoft.com/en-us/azure/devops/artifacts/npm/scopes?view=azure-devops&tabs=windows#set-up) if you are currently blocked by this.

**Comment by rdpolarity** [comment]
Same issue here as well

**Comment by murieletrentini** [comment]
Same issue here. And it was working so nicely for the past months

**Comment by nandin-borjigin** [comment]
`vsts-npm-auth` could be a replacement before the author fixes this issue.

**Comment by murieletrentini** [comment]
Not for non-windows users unfortunately :-(
vsts-npm-auth > _'The auth helper is currently only functional on a Windows machine'_

**Comment by beatzball** [comment]
seems the issue is not specific to this package but the oauth resource that is being used by default:
https://stateless-vsts-oauth.azurewebsites.net/

issue reported here:
https://github.com/zumwald/stateless-vsts-oauth/issues/12

the maintainer is no longer at MSFT, but i reached out to see if there's someone else that might be able to update the resource

**Comment by connorv001** [comment]
For anyone and everyone facing the same issue :
Here is a potential fix : 
1. Create an ADO App : https://app.vsaex.visualstudio.com/app/register
2. Note down the AppID and clientSecret somewhere secure. 
3. Fork this repo : https://github.com/zumwald/stateless-vsts-oauth.git
4. Modify the variables : https://github.com/zumwald/stateless-vsts-oauth/blob/main/index.js#L12
5. Rename the `main.handlebars` to 'main.hbs`
6. Save this under Github (In my case, I used ADO for easy deployment later on but it doesn't matter)
7. Using Azure App Services (or something similar) deploy this code and fetch the URL make sure it's https enabled. In Azure App Services, this will be a bit easier -- you've to either configure CD within app service or you can go ahead and and use any deployment method of your own
8. You will get a URL from AAS then just go ahead and configure the enviornmental variable for the same within our data that we generated from the 1st step.
9. Fork this repo:  https://github.com/zumwald/better-vsts-npm-auth.git
10. Modify the following:
    - https://github.com/zumwald/better-vsts-npm-auth/blob/main/package.json#L2
    - https://github.com/zumwald/better-vsts-npm-auth/blob/main/package.json#L15
    - https://github.com/zumwald/better-vsts-npm-auth/blob/main/lib/config.ts#L12 (Modify this section with the results you got from step 1)
 11. `npm publish` this package. 
This resolve the issue in my case 
⚠️  This will charge on your Azure App Services if you're using it.

**Comment by janpro0706** [comment]
@connorv001 

So instructive guides! But this can only works in single tenant which belongs to owned organization?

**Comment by connorv001** [comment]
> @connorv001
> 
> So instructive guides! But this can only works in single tenant which belongs to owned organization?

I'm not a 100% sure, my best guess would be not really tho.. Since it's an app on ado and not on aad but I could be wrong

**Comment by janpro0706** [comment]
@connorv001 

<img width="985" alt="스크린샷 2022-11-10 오전 3 48 44" src="https://user-images.githubusercontent.com/22425603/200916255-35cef444-e436-4b06-89f7-f429e0c59b4f.png">

I've got this error which I don't know it really indicates...
I will also dive into this issue, but if you have an idea to resolve this, please share your resolution.

**Comment by zumwald** [comment]
See https://github.com/zumwald/stateless-vsts-oauth/issues/12#issuecomment-1310682808

**Comment by nandin-borjigin** [comment]
Closing as duplicated of the issue https://github.com/zumwald/stateless-vsts-oauth/issues/12#issuecomment-1310682808
