### ISSUE TITLE
Getting started the first time is a little confusing-run the command again.

### ISSUE THREAD

**Issue by WieserSoftware** [zumwald/better-vsts-npm-auth#7]
After running better-vsts-npm-auth the first time, it said:
config from C:\Users\<REDACTED>\.npmrc
config from C:\ts\<REDACTED-PROJECT>\.npmrc
We need user consent before this script can run. Follow instructions in the browser window that just opened and then you can run this script again. If a browser does not open, paste https://app.vssps.visualstudio.com/oauth2/authorize?client_id=<REDACTED>&response_type=Assertion&state=<REDACTED>&scope=vso.packaging_write&redirect_uri=https://stateless-vsts-oauth.azurewebsites.net/oauth-callback into your browser window and follow the instructions to grant permissions.
Error: missing refresh_token
    at AuthorizationError (C:\Users\anwieser\AppData\Roaming\npm\node_modules\better-vsts-npm-auth\lib\vsts-auth-client.js:11:5)
    at Object.getUserAuthToken (C:\Users\anwieser\AppData\Roaming\npm\node_modules\better-vsts-npm-auth\lib\vsts-auth-client.js:48:27)
    at Function.authenticateRegistries (C:\Users\anwieser\AppData\Roaming\npm\node_modules\better-vsts-npm-auth\lib\registry-auth-reducer.js:148:29)
    at Promise.all.then.then.npmrcResults (C:\Users\anwieser\AppData\Roaming\npm\node_modules\better-vsts-npm-auth\index.js:64:57)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 
There's a lot of noise in there, and I totally missed the info about the running the script again.

Some line-breaks and visual delimiters, i.e., ***** might help, and reordering the  instruction to run it again to be after the instructions about the browser window, and before the error itself.

Especially as the browser window said this:
Success! Copy this command and run it in your terminal.
better-vsts-npm-auth config set refresh_token <TOKEN HERE>

 
I had kind of assumed that I had run the command again.
Maybe the browser window should add a second command to run it  again?
like this for example:

 better-vsts-npm-auth config set refresh_token <TOKEN HERE>; better-vsts-npm-auth

**Comment by WieserSoftware** [comment]
I propose changing the console.log statement to this:
console.log(
          "\n*****\n" +
          "We need user consent before this script can run.\n\n" +
          "Follow instructions in the browser window that just opened, or if a browser does not open,\n" +
          "manually browse to this url and follow the instructions there:\n\n" +
          `${consentUrl}\n\n` +
          "Then re-run this command again after consent has been granted.\n*****\n"
        );

**Comment by zumwald** [comment]
addressed in #8
